version: '2.3'
services:
  #======================================================
  # Database
  #======================================================
  db:
    container_name: db
    image: mariadb:10.1
    command: mysqld --character-set-server=utf8 --max_connections=1500
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - .database:/var/lib/mysql
      - ./voting-service-api/.docker/mariadb-conf:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=application
  #======================================================
  # Adminer
  #======================================================
  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 127.0.0.1:8080:8080
  #======================================================
  # Mailhog
  #======================================================
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 127.0.0.1:8025:8025
      - 127.0.0.1:1025:1025
